#!/bin/bash

# Portfolio Website Setup Guide
# Follow these steps to get your portfolio running

echo "============================================"
echo "  SIDDHANT'S PORTFOLIO - SETUP GUIDE"
echo "============================================"
echo ""

echo "📁 STEP 1: Copy all files to your Vite project"
echo "   Copy these files to your frontend/ directory:"
echo "   - src/App.jsx (replace existing)"
echo "   - src/index.css (replace existing)"
echo "   - src/components/ (entire folder)"
echo "   - README.md (for reference)"
echo ""

echo "📦 STEP 2: Install lucide-react for icons"
echo "   Run: npm install lucide-react"
echo ""

echo "🔗 STEP 3: Update your links (IMPORTANT!)"
echo "   Edit src/components/Projects.jsx:"
echo "   - Line 9: Change chat app GitHub link"
echo "   - Line 10: Change chat app live demo link"
echo "   - Line 24: Change AI app GitHub link"
echo "   - Line 25: Change AI app live demo link"
echo "   - Line 39: Change IPO tracker GitHub link"
echo "   - Line 40: Change IPO tracker live demo link"
echo "   - Line 54: Change drowsiness detection GitHub link"
echo ""

echo "📄 STEP 4: Add your resume PDF"
echo "   1. Place 'Siddhant_Gedekar_Resume.pdf' in public/ folder"
echo "   2. Or update the path in:"
echo "      - src/components/Hero.jsx (line 41)"
echo "      - src/components/Contact.jsx (line 94)"
echo ""

echo "🌐 STEP 5: Update LinkedIn URL (if you have one)"
echo "   Edit src/components/Hero.jsx line 32"
echo ""

echo "✅ STEP 6: Test everything"
echo "   Run: npm run dev"
echo "   Check:"
echo "   - All sections display correctly"
echo "   - Links work (GitHub, email, resume)"
echo "   - Mobile responsive (resize browser)"
echo ""

echo "🚀 STEP 7: Deploy"
echo "   Option A - Netlify:"
echo "   1. Run: npm run build"
echo "   2. Drag dist/ folder to netlify.com/drop"
echo ""
echo "   Option B - Vercel:"
echo "   1. Push to GitHub"
echo "   2. Import on vercel.com"
echo ""

echo "============================================"
echo "  QUICK REFERENCE"
echo "============================================"
echo ""
echo "File Structure:"
echo "frontend/"
echo "├── src/"
echo "│   ├── App.jsx              ← Main component"
echo "│   ├── index.css            ← Styles"
echo "│   └── components/"
echo "│       ├── Hero.jsx         ← Landing page"
echo "│       ├── About.jsx        ← About section"
echo "│       ├── Skills.jsx       ← Tech skills"
echo "│       ├── Projects.jsx     ← Your projects"
echo "│       ├── Experience.jsx   ← Work history"
echo "│       ├── Contact.jsx      ← Contact info"
echo "│       └── Footer.jsx       ← Footer"
echo "├── public/"
echo "│   └── Siddhant_Gedekar_Resume.pdf  ← Add this!"
echo "└── package.json"
echo ""

echo "============================================"
echo "  WHAT TO UPDATE BEFORE DEPLOYING"
echo "============================================"
echo ""
echo "✓ GitHub links in Projects.jsx"
echo "✓ Live demo links in Projects.jsx"
echo "✓ Resume PDF in public/ folder"
echo "✓ LinkedIn URL in Hero.jsx (optional)"
echo ""

echo "Need help? Check README.md for detailed instructions"
echo ""
